### ISSUE TITLE
In Chrome if user selects the "Remember my choice for all links of this type" check box the fail callback always gets called.

### ISSUE THREAD

**Issue by spstratis** [ismailhabib/custom-protocol-detection#1]
Hi there, first off this js file is really useful, great job on it. I have run across a problem though now that I have implemented it my self. Details below:

Chrome ver. 42.0.2311.90 m / Windows

If a user selects the "Remember my choice for all links of this type" check box in the browser default protocol handler alert from there on when ever the protocolCheck method is called it will always run the fail callback as well as opening the app associated with the protocol handler. I believe this is due to the time out checking on if that dialog opens or not after a certain amount of time, but have not had the opportunity to dig further into the issue.

**Comment by ismailhabib** [comment]
Hi spstratis, thanks for the feedback!

You are absolutely right, this Chrome implementation is based on the assumption that there will be app loaded by the custom protocol handler and thus will steal the focus from the window. Could you tell me what the behavior of your protocol handler in this case?

**Comment by spstratis** [comment]
For me the protocol handler is opening a windows app. It opens it successfully yet the fail call back still fires off as if focus is not being put on to the app the is opening.

**Comment by ismailhabib** [comment]
That sounds strange. Could you do a bit more debugging to see whether the onBlur method is being triggered at all? One possibility is that the app is slow to load (need more than a second) or the loaded app doesn't take the focus at all.

**Comment by spstratis** [comment]
Yea I was thinking of adding additional time to the timeout and checking to see if that makes a difference.  I'll let you know the result of some additional debugging.

**Comment by spstratis** [comment]
So far it looks like setting the time out to 2000 takes care of the issue.

**Comment by spstratis** [comment]
You were right the loaded app was not taking focus. I notice from time to time it will still hit the failure state but I believe that may be due to propagation on the button click to launch the app. You should feel free to close this defect. Thanks for responding back!

**Comment by Methiau** [comment]
Hi Ismail Habib

we have exactly the same problem, but we can't find a way around it. even if we increase the timeout, the behaviour is the same. The app is launched _and_ the call back fail function. Hope i didn't misunderstood somthing crucial.
