### ISSUE TITLE
line 187 - url should be uri

### ISSUE THREAD

**Issue by justinbangerter** [ismailhabib/custom-protocol-detection#15]
```
 window.protocolCheck = function(uri, failCb, successCb) {
... 
openUriWithMsLaunchUri(url, failCb, successCb);
```

should be uri, not url - otherwise, edge throws 'url is undefined'

Awesome library.  Thank you!  I'd buy you a beer if I could.

**Comment by justinbangerter** [comment]
oh yeah, found another one: 147 - need to add a successcb parameter

**Comment by ismailhabib** [comment]
Good findings, thanks a lot!

Commit: 535e459c18bc532299d701a72bd999720383d7fa
