### ISSUE TITLE
Nothing for Safari

### ISSUE THREAD

**Issue by spignataro** [ismailhabib/custom-protocol-detection#2]
I noticed there isn't anything for safari. So instead I used what Chrome was using and it works perfectly. I would suggest to put this into the package as it was very helpful. Although if the app doesn't exist this is where I am having a problem. So it would be great to have safari support soon.

**Comment by ismailhabib** [comment]
Thanks for the feedback. Unfortunately I don't know if there exists a technical solution for Safari (without plugin) since it always open an error page whenever the custom handler is not available.

If you know a solution for this, I'd like to hear about it!
