### ISSUE TITLE
Just for you to know, since IE10 there is msLaunchURI which has a "noHandlerCallback"

### ISSUE THREAD

**Issue by ArfyFR** [ismailhabib/custom-protocol-detection#3]
See:
https://msdn.microsoft.com/en-us/library/jj154912(v=vs.85).aspx

Regards,
Arfy

**Comment by ismailhabib** [comment]
That's what I've been using for IE running on Windows 8 (should check whether this is still the case with Windows 10). However, this is not available in any version of IE in older version than Windows 8. See: http://stackoverflow.com/questions/23396303/mslaunchuri-not-available-in-ie11

**Comment by zowers** [comment]
works in windows 10 on internet explorer 11 and edge
btw, it's better to test `if( navigator.msLaunchUri )` instead of user agent checks

**Comment by ismailhabib** [comment]
That's exactly what I did (or I misunderstand something here?). I will update the script with IE in windows 10 (and possibly Edge) when I have time. Pull request is also welcome :)

**Comment by zowers** [comment]
no, you first check user agent:

```
        var isWin8 = /windows nt 6.2/.test(ua) || /windows nt 6.3/.test(ua);

        if (isWin8) {
            openUriUsingIEInWindows8(uri, failCb);
```

which is not needed, you can check `navigator.msLaunchUri` directly instead

```
    window.protocolCheck = function (uri, failCb) {
        var browser = checkBrowser();

        function failCallback() {
            failCb && failCb();
        }

        if (navigator.msLaunchUri)
          navigator.msLaunchUri( uri, function() {}, failCallback );
        if (browser.isFirefox) {
            openUriUsingFirefox(uri, failCallback);
        } else if (browser.isChrome) {
            openUriWithTimeoutHack(uri, failCallback);
        } else if (browser.isIE) {
            openUriUsingIE(uri, failCallback);
        } else {
            //not supported, implement please
        }
    }
```

**Comment by ismailhabib** [comment]
Implemented.

**Comment by qiulang** [comment]
I found that some version of IE 11 on win10 does not have this method.
