### ISSUE TITLE
Does not work with Safari

### ISSUE THREAD

**Issue by kirill-konshin** [ismailhabib/custom-protocol-detection#30]
Because of browser detection `ifs` in Safari nothing is launched, neither success nor fail callback:

https://github.com/ismailhabib/custom-protocol-detection/blob/master/protocolcheck.js#L197

```js
    if (navigator.msLaunchUri) { //for IE and Edge in Win 8 and Win 10
        openUriWithMsLaunchUri(uri, failCb, successCb);
    } else {
        var browser = checkBrowser();

        if (browser.isFirefox) {
            openUriUsingFirefox(uri, failCallback, successCallback);
        } else if (browser.isChrome) {
            openUriWithTimeoutHack(uri, failCallback, successCallback);
        } else if (browser.isIE) {
            openUriUsingIEInOlderWindows(uri, failCallback, successCallback);
        } else {
            //not supported, implement please
        }
    }
```

Instead of commented line a failure callback has to be called or a new, third type has to be introduced.

Moreover the check returns following browser object:

```
isChrome: false
isFirefox: false
isIE: false
isOpera: false
isSafari: false
```

Safari version is 10.1.2 (12603.3.8).

**Comment by kirill-konshin** [comment]
Bump!

**Comment by jpiepkow** [comment]
@kirill-konshin you should put a pull request or publish your fork to npm so people that need this feature can use it.

**Comment by kirill-konshin** [comment]
Yep, looks like this project is not maintained...
