### ISSUE TITLE
Success callback

### ISSUE THREAD

**Issue by sraimund** [ismailhabib/custom-protocol-detection#6]
Could you implement a `successCb` analog to `failCb`? `successCb` should be called when the custom protocol has been recognized.

This would help to inform users that the external application has been started.

**Comment by ismailhabib** [comment]
Unfortunately this is technically not possible since most of the browsers don't support it.

**Comment by sraimund** [comment]
It does not need to be supported by the browser, but it could be implemented in your code when the `failCb` is not called, which means that the protocol seems to be recognized successfully. The `successCb` may occur in some cases after a certain timeout. I was thinking about something similar to this code: https://gist.github.com/rajeshsegu/3716941

**Comment by vladimirtsyupko** [comment]
Here's my gist for this 
https://gist.github.com/vladimirtsyupko/cfcd332476b16683bb0b

**Comment by ismailhabib** [comment]
Can you create a pull request for this?

**Comment by sraimund** [comment]
Thanks @vladimirtsyupko!

While testing however, I noticed that you forgot `successCb` in the `openUriUsingIEInOlderWindows` function.

Also to ensure backwards compatibility, it might be better to have the argument `failCb` before `successCb` in the `protocolCheck` function. What do you think about this, @ismailhabib?

**Comment by ismailhabib** [comment]
@sraimund: while backward compatibility is good, I think at this moment I won't be too worried about it. A proper versioning and documentation should be enough.

**Comment by vladimirtsyupko** [comment]
@ismailhabib , @sraimund yes, going to do it when I have some free time!
