### ISSUE TITLE
Edge and msLaunchUri

### ISSUE THREAD

**Issue by yoisn** [ismailhabib/custom-protocol-detection#7]
This project is amazing!!!  I like the way you used onBlur for Chrome.

I'm having a problem with msLaunchUri in Edge on Windows 10 (obviously) but the problem doesn't appear in IE on Win10.  In IE it works as designed, calling the success and fail functions properly.  But in Edge, nothing happens at all.  I've modified your code slightly (as I can't use jquery to call your functions) and here it is:
`if (navigator.msLaunchUri) {
            alert('msLaunchUri is true');
            navigator.msLaunchUri(url, 
                   function(){ console.log('dwrc protocol found'); }, //success
                   function(){ startAutoDownload(url);  }  //failure 
            );`

The alert fires, so I know the if statement is working. I also can see from the F12 menu that the url value is correct.  But the program doesn't launch, nothing gets written to the console, and the download doesn't start.  Even though the exact same code works in IE.

Any ideas?
P.S. how do I get the line breaks in my code to show in the post?

**Comment by yoisn** [comment]
I figured out the problem.

it seems that msLaunchUri in Edge only gives you one chance per load of the affected protocol.  If it wasn't installed, the web page loaded, and then you installed it, msLaunchUri does absolutely nothing, even if you refresh the page.  IE11 in Windows 10 behaves differently.

**Comment by djpereira** [comment]
This issue is probably caused by this: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7181860/
