### ISSUE TITLE
Request for OSS license

### ISSUE THREAD

**Issue by mattlebeau** [ismailhabib/custom-protocol-detection#9]
Hi Ismailhabib,

One of my teams would like to use your custom-protocol-detection library in a project, though is unable to without a specific OSS license being stipulated.
Would you be open to the idea of adding a license like MIT or Apache 2.0 to this project?

Thank you for this fantastic bit of software engineering, sir!

**Comment by ismailhabib** [comment]
Done.

**Comment by mattlebeau** [comment]
Thank you!!
